<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrZgxSX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrZgxSX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCrZgxSX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCrZgxSX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCrZgxSX\App_KernelDevDebugContainer([
    'container.build_hash' => 'CrZgxSX',
    'container.build_id' => 'a3bfb508',
    'container.build_time' => 1628118485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrZgxSX');
