<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP5QdUHf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP5QdUHf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP5QdUHf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP5QdUHf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP5QdUHf\App_KernelDevDebugContainer([
    'container.build_hash' => 'P5QdUHf',
    'container.build_id' => 'fd00f334',
    'container.build_time' => 1627947136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP5QdUHf');
