<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHb7dPEq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHb7dPEq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHb7dPEq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHb7dPEq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHb7dPEq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hb7dPEq',
    'container.build_id' => '846ce4fa',
    'container.build_time' => 1628120911,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHb7dPEq');
